package dev.diego.expanda.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import dev.diego.expanda.data.DisplayLanguage
import java.util.Locale

val LocalDisplayLanguage = staticCompositionLocalOf { DisplayLanguage.SYSTEM }

object UiDisplayLanguage {
    @Volatile
    var current: DisplayLanguage = DisplayLanguage.SYSTEM
}

fun setUiDisplayLanguage(language: DisplayLanguage) {
    UiDisplayLanguage.current = language
}

fun usesSpanish(language: DisplayLanguage): Boolean = when (language) {
    DisplayLanguage.SPANISH -> true
    DisplayLanguage.ENGLISH -> false
    DisplayLanguage.SYSTEM -> Locale.getDefault().language.equals("es", ignoreCase = true)
}

fun translate(language: DisplayLanguage, english: String, spanish: String): String =
    if (usesSpanish(language)) spanish else english

fun uiText(english: String, spanish: String): String =
    translate(UiDisplayLanguage.current, english, spanish)

fun uiText(english: String): String {
    if (!usesSpanish(UiDisplayLanguage.current)) return english
    return SPANISH[english] ?: english
}

@Composable
fun tr(english: String, spanish: String): String =
    translate(UiDisplayLanguage.current, english, spanish)

@Composable
fun tr(english: String): String {
    if (!usesSpanish(UiDisplayLanguage.current)) return english
    return SPANISH[english] ?: english
}

private val SPANISH = mapOf(
    "Snippets" to "Fragmentos",
    "Playground" to "Pruebas",
    "Actions" to "Acciones",
    "Source" to "Fuente",
    "Settings" to "Ajustes",
    "Delete" to "Eliminar",
    "Cancel" to "Cancelar",
    "Save" to "Guardar",
    "Done" to "Listo",
    "Add" to "Agregar",
    "Clear" to "Limpiar",
    "Close" to "Cerrar",
    "Back" to "Atrás",
    "Continue" to "Continuar",
    "Not now" to "Ahora no",
    "Enable" to "Activar",
    "Disable" to "Desactivar",
    "All" to "Todos",
    "None" to "Ninguno",
    "Selected" to "Seleccionados",
    "Search apps" to "Buscar aplicaciones",
    "Add package" to "Agregar paquete",
    "Package name" to "Nombre del paquete",
    "Advanced fallback, for example com.example.app" to "Alternativa avanzada, por ejemplo com.example.app",
    "Enable all" to "Activar todas",
    "Disable all" to "Desactivar todas",
    "Edit shortcut" to "Editar atajo",
    "Edit action shortcut" to "Editar atajo de acción",
    "Shortcut" to "Atajo",
    "Restore default" to "Restaurar predeterminado",
    "About Expanda" to "Acerca de Expanda",
    "Project, source code and contact links" to "Proyecto, código fuente y enlaces de contacto",
    "Learn Expanda" to "Aprender Expanda",
    "Reopen the animated introduction" to "Volver a abrir la introducción animada",
    "Text expansion" to "Expansión de texto",
    "Accessibility service" to "Servicio de accesibilidad",
    "Run reliably in background" to "Ejecutar de forma fiable en segundo plano",
    "Ready" to "Listo",
    "Required" to "Requerido",
    "Resume now" to "Reanudar ahora",
    "Pause for one hour" to "Pausar por una hora",
    "Excluded apps" to "Aplicaciones excluidas",
    "Clipboard history" to "Historial del portapapeles",
    "Save copied text for clipboard snippets in other apps" to "Guardar texto copiado para fragmentos de portapapeles en otras aplicaciones",
    "Haptic feedback" to "Respuesta háptica",
    "Compatibility paste fallback" to "Alternativa de pegado por compatibilidad",
    "For editors that reject direct replacement. Temporarily uses and restores the clipboard." to "Para editores que rechazan el reemplazo directo. Usa temporalmente el portapapeles y luego lo restaura.",
    "Selection toolbar" to "Barra de selección",
    "Show quick text transformations when you select editable text" to "Mostrar transformaciones rápidas al seleccionar texto editable",
    "Statistics" to "Estadísticas",
    "Appearance" to "Apariencia",
    "Display language" to "Idioma de visualización",
    "Color scheme" to "Esquema de color",
    "Theme mode" to "Modo de tema",
    "Import & export" to "Importar y exportar",
    "Import" to "Importar",
    "Export" to "Exportar",
    "Sync now" to "Sincronizar ahora",
    "Unlink" to "Desvincular",
    "Open Espanso source files" to "Abrir archivos fuente de Espanso",
    "Full app backup" to "Copia de seguridad completa",
    "Restore" to "Restaurar",
    "Back up" to "Crear copia",
    "Import snippets from CSV" to "Importar fragmentos desde CSV",
    "Export snippets as CSV" to "Exportar fragmentos como CSV",
    "Privacy" to "Privacidad",
    "All snippets stay on this device. Password fields are ignored. No analytics or network access." to "Todos los fragmentos permanecen en este dispositivo. Se ignoran los campos de contraseña. Sin analíticas ni acceso a red.",
    "Clear clipboard history" to "Limpiar historial del portapapeles",
    "Reset usage statistics" to "Restablecer estadísticas de uso",
    "Diagnostics copied" to "Diagnóstico copiado",
    "Copy diagnostics" to "Copiar diagnóstico",
    "Version and device state only; no text, clipboard or app names" to "Sólo versión y estado del dispositivo; sin texto, portapapeles ni nombres de aplicaciones",
    "Reset Expanda" to "Restablecer Expanda",
    "Delete local data and return to the first-run tutorial" to "Eliminar datos locales y volver al tutorial inicial",
    "Selection toolbar size" to "Tamaño de la barra de selección",
    "Reset layout" to "Restablecer diseño",
    "Width" to "Ancho",
    "Height" to "Alto",
    "Text size" to "Tamaño del texto",
    "Reset" to "Restablecer",
    "Smaller" to "Más pequeño",
    "Larger" to "Más grande",
    "Insert into replacement" to "Insertar en el reemplazo",
    "Name (optional)" to "Nombre (opcional)",
    "Regex trigger" to "Disparador regex",
    "Trigger" to "Disparador",
    "Use regular expression matching" to "Usar coincidencia por expresión regular",
    "Match uppercase and lowercase exactly" to "Distinguir exactamente mayúsculas y minúsculas",
    "Replacements" to "Reemplazos",
    "Add replacement" to "Agregar reemplazo",
    "Add tag" to "Agregar etiqueta",
    "Existing or new tag" to "Etiqueta existente o nueva",
    "Allow Expanda to run in background" to "Permitir que Expanda se ejecute en segundo plano",
    "Open battery settings" to "Abrir ajustes de batería",
    "I've configured it" to "Ya lo configuré",
    "How text expansion works" to "Cómo funciona la expansión de texto",
    "Couldn't enable Accessibility?" to "¿No pudiste activar Accesibilidad?",
    "Open App info" to "Abrir información de la app",
    "Open Accessibility again" to "Abrir Accesibilidad otra vez",
    "I don't have that option" to "No tengo esa opción",
    "No transformation changes this selection." to "Ninguna transformación cambia esta selección.",
    "Use" to "Usar",
    "Activation delimiters" to "Delimitadores de activación",
    "Match letter case exactly" to "Distinguir mayúsculas y minúsculas",
    "Alternative triggers" to "Disparadores alternativos",
    "One per line; use regex: before a regular expression" to "Uno por línea; usa regex: antes de una expresión regular",
    "Search terms" to "Términos de búsqueda",
    "Separate terms with commas" to "Separa los términos con comas",
    "Duplicate" to "Duplicar",
    "Edit tags" to "Editar etiquetas",
    "Delete tags" to "Eliminar etiquetas",
    "Apply" to "Aplicar",
    "Espanso source" to "Fuente de Espanso",
    "Guide" to "Guía",
    "Copy" to "Copiar",
    "Open" to "Abrir",
    "Save source" to "Guardar fuente",
    "Discard" to "Descartar",
    "Keep editing" to "Seguir editando",
    "Source and AI guide" to "Fuente y guía de IA",
    "Copy AI prompt" to "Copiar instrucción para IA",
    "Change folder" to "Cambiar carpeta",
    "Link folder" to "Vincular carpeta",
    "Sync folder" to "Sincronizar carpeta",
    "Suggestion overlay" to "Panel de sugerencias",
    "Show matching snippets while you type" to "Mostrar fragmentos coincidentes mientras escribes",
    "Show actions in suggestions" to "Mostrar acciones en sugerencias",
    "Include enabled actions alongside text snippets" to "Incluir acciones activadas junto a los fragmentos de texto",
    "Compact list" to "Lista compacta",
    "Compact suggestion list" to "Lista compacta de sugerencias",
    "Off shows the replacement preview" to "Desactivado muestra la vista previa del reemplazo",
    "Minimum characters" to "Caracteres mínimos",
    "Minimum matching characters" to "Caracteres mínimos de coincidencia",
    "Resize button" to "Botón de redimensionar",
    "Show popup resize button" to "Mostrar botón para redimensionar el panel",
    "Drag the bottom-left control diagonally to resize width and height" to "Arrastra diagonalmente el control inferior izquierdo para cambiar ancho y alto",
    "Match suggestions from beginning" to "Coincidir sugerencias desde el inicio",
    "Turn off to match text anywhere in a shortcut" to "Desactiva para coincidir texto en cualquier parte del atajo",
    "Suggestion popup size" to "Tamaño del panel de sugerencias",
    "Open suggestion overlay" to "Abrir panel de sugerencias",
    "Expanda writing playground" to "Área de pruebas de escritura de Expanda",
    "Numbers and calculations" to "Números y cálculos",
    "Text" to "Texto",
    "Selection" to "Selección",
    "Deletion" to "Eliminación",
    "Cursor" to "Cursor",
    "Clipboard" to "Portapapeles",
    "Also available from Android's selected-text menu" to "También disponible desde el menú de texto seleccionado de Android",
    "The shortcut cannot be empty" to "El atajo no puede estar vacío",
    "Another action already uses this shortcut" to "Otra acción ya usa este atajo",
    "Append calculation result" to "Añadir resultado del cálculo",
    "Keep the expression and append its result" to "Conservar la expresión y añadir su resultado",
    "Calculate expression" to "Calcular expresión",
    "Replace the last math expression with its result" to "Reemplazar la última expresión matemática por su resultado",
    "Space thousands" to "Miles con espacios",
    "Period thousands" to "Miles con punto",
    "Comma thousands" to "Miles con coma",
    "Remove diacritics" to "Quitar diacríticos",
    "Convert áéñ to aen" to "Convertir áéñ en aen",
    "Uppercase" to "Mayúsculas",
    "Convert all text to uppercase" to "Convertir todo el texto a mayúsculas",
    "Lowercase" to "Minúsculas",
    "Convert all text to lowercase" to "Convertir todo el texto a minúsculas",
    "Uppercase previous word" to "Palabra anterior en mayúsculas",
    "Convert only the previous word to uppercase" to "Convertir sólo la palabra anterior a mayúsculas",
    "Lowercase previous word" to "Palabra anterior en minúsculas",
    "Convert only the previous word to lowercase" to "Convertir sólo la palabra anterior a minúsculas",
    "Capitalize previous word" to "Capitalizar palabra anterior",
    "Capitalize only the previous word" to "Poner en mayúscula sólo la inicial de la palabra anterior",
    "Vault" to "Bóveda",
    "Open vault" to "Abrir bóveda",
    "Open the encrypted Expanda vault" to "Abrir la bóveda cifrada de Expanda",
    "Sentence case" to "Tipo oración",
    "Capitalize each sentence" to "Capitalizar cada oración",
    "Capitalize words" to "Capitalizar palabras",
    "Capitalize the first letter of every word" to "Capitalizar la primera letra de cada palabra",
    "Spaces to underscores" to "Espacios a guiones bajos",
    "Replace spaces with underscores" to "Reemplazar espacios por guiones bajos",
    "Spaces to dashes" to "Espacios a guiones",
    "Replace spaces with dashes" to "Reemplazar espacios por guiones",
    "Underscores to spaces" to "Guiones bajos a espacios",
    "Replace underscores with spaces" to "Reemplazar guiones bajos por espacios",
    "Dashes to spaces" to "Guiones a espacios",
    "Replace dashes with spaces" to "Reemplazar guiones por espacios",
    "Generate UUID" to "Generar UUID",
    "Replace the current text or selection with a UUID" to "Reemplazar el texto actual o la selección por un UUID",
    "Select all" to "Seleccionar todo",
    "Select all remaining text" to "Seleccionar todo el texto restante",
    "Select before cursor" to "Seleccionar antes del cursor",
    "Select from the start to the cursor" to "Seleccionar desde el inicio hasta el cursor",
    "Select after cursor" to "Seleccionar después del cursor",
    "Select from the cursor to the end" to "Seleccionar desde el cursor hasta el final",
    "Delete all" to "Eliminar todo",
    "Delete all text" to "Eliminar todo el texto",
    "Delete before cursor" to "Eliminar antes del cursor",
    "Delete from the start to the cursor" to "Eliminar desde el inicio hasta el cursor",
    "Delete after cursor" to "Eliminar después del cursor",
    "Delete from the cursor to the end" to "Eliminar desde el cursor hasta el final",
    "Trim spaces" to "Quitar espacios de los extremos",
    "Delete leading and trailing spaces" to "Eliminar espacios al inicio y al final",
    "Remove all spaces" to "Eliminar todos los espacios",
    "Delete every whitespace character" to "Eliminar todos los caracteres en blanco",
    "Delete blank lines" to "Eliminar líneas vacías",
    "Remove empty lines" to "Eliminar líneas vacías",
    "Remove duplicate lines" to "Eliminar líneas duplicadas",
    "Keep the first occurrence of each line" to "Conservar la primera aparición de cada línea",
    "Remove duplicate words" to "Eliminar palabras duplicadas",
    "Keep the first occurrence of each word" to "Conservar la primera aparición de cada palabra",
    "Remove line breaks" to "Quitar saltos de línea",
    "Join lines with spaces" to "Unir líneas con espacios",
    "Sort lines" to "Ordenar líneas",
    "Sort selected lines alphabetically" to "Ordenar alfabéticamente las líneas seleccionadas",
    "Number lines" to "Numerar líneas",
    "Add sequential numbers to lines" to "Agregar números consecutivos a las líneas",
    "Reverse text" to "Invertir texto",
    "Reverse all selected characters" to "Invertir todos los caracteres seleccionados",
    "Reverse lines" to "Invertir líneas",
    "Reverse the order of selected lines" to "Invertir el orden de las líneas seleccionadas",
    "Reverse words" to "Invertir palabras",
    "Reverse the order of selected words" to "Invertir el orden de las palabras seleccionadas",
    "Cursor to start" to "Cursor al inicio",
    "Place the cursor at the start" to "Colocar el cursor al inicio",
    "Cursor to end" to "Cursor al final",
    "Place the cursor at the end" to "Colocar el cursor al final",
    "Copy all" to "Copiar todo",
    "Copy all text" to "Copiar todo el texto",
    "Paste" to "Pegar",
    "Paste clipboard text" to "Pegar texto del portapapeles",
    "Copy before cursor" to "Copiar antes del cursor",
    "Copy from start to cursor" to "Copiar desde el inicio hasta el cursor",
    "Copy after cursor" to "Copiar después del cursor",
    "Copy from cursor to end" to "Copiar desde el cursor hasta el final",
    "Paste numbers" to "Pegar números",
    "Paste only numeric characters" to "Pegar sólo caracteres numéricos",
    "Cut all" to "Cortar todo",
    "Cut all text" to "Cortar todo el texto",
    "Cut before cursor" to "Cortar antes del cursor",
    "Cut from start to cursor" to "Cortar desde el inicio hasta el cursor",
    "Cut after cursor" to "Cortar después del cursor",
    "Cut from cursor to end" to "Cortar desde el cursor hasta el final",
    "Share" to "Compartir",
    "Open Android's share sheet" to "Abrir el menú de compartir de Android",
    "New snippet" to "Nuevo fragmento",
    "Open Expanda's new snippet editor" to "Abrir el editor de nuevo fragmento de Expanda",
    "Insert clipboard" to "Insertar portapapeles",
    "Insert the latest copied text" to "Insertar el último texto copiado",
    "Toggle suggestions" to "Alternar sugerencias",
    "Enable or disable the suggestion overlay" to "Activar o desactivar el panel de sugerencias"
)
