package dev.diego.expanda.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import dev.diego.expanda.data.DisplayLanguage
import java.util.Locale

val LocalDisplayLanguage = staticCompositionLocalOf { DisplayLanguage.SYSTEM }

fun usesSpanish(language: DisplayLanguage): Boolean = when (language) {
    DisplayLanguage.SPANISH -> true
    DisplayLanguage.ENGLISH -> false
    DisplayLanguage.SYSTEM -> Locale.getDefault().language.equals("es", ignoreCase = true)
}

fun translate(language: DisplayLanguage, english: String, spanish: String): String =
    if (usesSpanish(language)) spanish else english

@Composable
fun tr(english: String, spanish: String): String =
    translate(LocalDisplayLanguage.current, english, spanish)

@Composable
fun tr(english: String): String {
    if (!usesSpanish(LocalDisplayLanguage.current)) return english
    return SPANISH[english] ?: english
}

private val SPANISH = mapOf(
    "Snippets" to "Fragmentos",
    "Playground" to "Pruebas",
    "Actions" to "Acciones",
    "Source" to "Fuente",
    "Settings" to "Ajustes",
    "Delete" to "Eliminar",
    "Cancel" to "Cancelar",
    "Save" to "Guardar",
    "Done" to "Listo",
    "Add" to "Agregar",
    "Clear" to "Limpiar",
    "Close" to "Cerrar",
    "Back" to "Atrás",
    "Continue" to "Continuar",
    "Not now" to "Ahora no",
    "Enable" to "Activar",
    "Disable" to "Desactivar",
    "All" to "Todos",
    "None" to "Ninguno",
    "Selected" to "Seleccionados",
    "Search apps" to "Buscar aplicaciones",
    "Add package" to "Agregar paquete",
    "Package name" to "Nombre del paquete",
    "Advanced fallback, for example com.example.app" to "Alternativa avanzada, por ejemplo com.example.app",
    "Enable all" to "Activar todas",
    "Disable all" to "Desactivar todas",
    "Edit shortcut" to "Editar atajo",
    "Edit action shortcut" to "Editar atajo de acción",
    "Shortcut" to "Atajo",
    "Restore default" to "Restaurar predeterminado",
    "About Expanda" to "Acerca de Expanda",
    "Project, source code and contact links" to "Proyecto, código fuente y enlaces de contacto",
    "Learn Expanda" to "Aprender Expanda",
    "Reopen the animated introduction" to "Volver a abrir la introducción animada",
    "Text expansion" to "Expansión de texto",
    "Accessibility service" to "Servicio de accesibilidad",
    "Run reliably in background" to "Ejecutar de forma fiable en segundo plano",
    "Ready" to "Listo",
    "Required" to "Requerido",
    "Resume now" to "Reanudar ahora",
    "Pause for one hour" to "Pausar por una hora",
    "Excluded apps" to "Aplicaciones excluidas",
    "Clipboard history" to "Historial del portapapeles",
    "Save copied text for clipboard snippets in other apps" to "Guardar texto copiado para fragmentos de portapapeles en otras aplicaciones",
    "Haptic feedback" to "Respuesta háptica",
    "Compatibility paste fallback" to "Alternativa de pegado por compatibilidad",
    "For editors that reject direct replacement. Temporarily uses and restores the clipboard." to "Para editores que rechazan el reemplazo directo. Usa temporalmente el portapapeles y luego lo restaura.",
    "Selection toolbar" to "Barra de selección",
    "Show quick text transformations when you select editable text" to "Mostrar transformaciones rápidas al seleccionar texto editable",
    "Statistics" to "Estadísticas",
    "Appearance" to "Apariencia",
    "Display language" to "Idioma de visualización",
    "Color scheme" to "Esquema de color",
    "Theme mode" to "Modo de tema",
    "Import & export" to "Importar y exportar",
    "Import" to "Importar",
    "Export" to "Exportar",
    "Sync now" to "Sincronizar ahora",
    "Unlink" to "Desvincular",
    "Open Espanso source files" to "Abrir archivos fuente de Espanso",
    "Full app backup" to "Copia de seguridad completa",
    "Restore" to "Restaurar",
    "Back up" to "Crear copia",
    "Import snippets from CSV" to "Importar fragmentos desde CSV",
    "Export snippets as CSV" to "Exportar fragmentos como CSV",
    "Privacy" to "Privacidad",
    "All snippets stay on this device. Password fields are ignored. No analytics or network access." to "Todos los fragmentos permanecen en este dispositivo. Se ignoran los campos de contraseña. Sin analíticas ni acceso a red.",
    "Clear clipboard history" to "Limpiar historial del portapapeles",
    "Reset usage statistics" to "Restablecer estadísticas de uso",
    "Diagnostics copied" to "Diagnóstico copiado",
    "Copy diagnostics" to "Copiar diagnóstico",
    "Version and device state only; no text, clipboard or app names" to "Sólo versión y estado del dispositivo; sin texto, portapapeles ni nombres de aplicaciones",
    "Reset Expanda" to "Restablecer Expanda",
    "Delete local data and return to the first-run tutorial" to "Eliminar datos locales y volver al tutorial inicial",
    "Selection toolbar size" to "Tamaño de la barra de selección",
    "Reset layout" to "Restablecer diseño",
    "Width" to "Ancho",
    "Height" to "Alto",
    "Text size" to "Tamaño del texto",
    "Reset" to "Restablecer",
    "Smaller" to "Más pequeño",
    "Larger" to "Más grande",
    "Insert into replacement" to "Insertar en el reemplazo",
    "Name (optional)" to "Nombre (opcional)",
    "Regex trigger" to "Disparador regex",
    "Trigger" to "Disparador",
    "Use regular expression matching" to "Usar coincidencia por expresión regular",
    "Match uppercase and lowercase exactly" to "Distinguir exactamente mayúsculas y minúsculas",
    "Replacements" to "Reemplazos",
    "Add replacement" to "Agregar reemplazo",
    "Add tag" to "Agregar etiqueta",
    "Existing or new tag" to "Etiqueta existente o nueva",
    "Allow Expanda to run in background" to "Permitir que Expanda se ejecute en segundo plano",
    "Open battery settings" to "Abrir ajustes de batería",
    "I've configured it" to "Ya lo configuré",
    "How text expansion works" to "Cómo funciona la expansión de texto",
    "Couldn't enable Accessibility?" to "¿No pudiste activar Accesibilidad?",
    "Open App info" to "Abrir información de la app",
    "Open Accessibility again" to "Abrir Accesibilidad otra vez",
    "I don't have that option" to "No tengo esa opción",
    "No transformation changes this selection." to "Ninguna transformación cambia esta selección.",
    "Use" to "Usar",
    "Activation delimiters" to "Delimitadores de activación",
    "Match letter case exactly" to "Distinguir mayúsculas y minúsculas",
    "Alternative triggers" to "Disparadores alternativos",
    "One per line; use regex: before a regular expression" to "Uno por línea; usa regex: antes de una expresión regular",
    "Search terms" to "Términos de búsqueda",
    "Separate terms with commas" to "Separa los términos con comas",
    "Duplicate" to "Duplicar",
    "Edit tags" to "Editar etiquetas",
    "Delete tags" to "Eliminar etiquetas",
    "Apply" to "Aplicar",
    "Espanso source" to "Fuente de Espanso",
    "Guide" to "Guía",
    "Copy" to "Copiar",
    "Open" to "Abrir",
    "Save source" to "Guardar fuente",
    "Discard" to "Descartar",
    "Keep editing" to "Seguir editando",
    "Source and AI guide" to "Fuente y guía de IA",
    "Copy AI prompt" to "Copiar instrucción para IA",
    "Change folder" to "Cambiar carpeta",
    "Link folder" to "Vincular carpeta",
    "Sync folder" to "Sincronizar carpeta",
    "Suggestion overlay" to "Panel de sugerencias",
    "Show matching snippets while you type" to "Mostrar fragmentos coincidentes mientras escribes",
    "Show actions in suggestions" to "Mostrar acciones en sugerencias",
    "Include enabled actions alongside text snippets" to "Incluir acciones activadas junto a los fragmentos de texto",
    "Compact list" to "Lista compacta",
    "Compact suggestion list" to "Lista compacta de sugerencias",
    "Off shows the replacement preview" to "Desactivado muestra la vista previa del reemplazo",
    "Minimum characters" to "Caracteres mínimos",
    "Minimum matching characters" to "Caracteres mínimos de coincidencia",
    "Resize button" to "Botón de redimensionar",
    "Show popup resize button" to "Mostrar botón para redimensionar el panel",
    "Drag the bottom-left control diagonally to resize width and height" to "Arrastra diagonalmente el control inferior izquierdo para cambiar ancho y alto",
    "Match suggestions from beginning" to "Coincidir sugerencias desde el inicio",
    "Turn off to match text anywhere in a shortcut" to "Desactiva para coincidir texto en cualquier parte del atajo",
    "Suggestion popup size" to "Tamaño del panel de sugerencias",
    "Open suggestion overlay" to "Abrir panel de sugerencias",
    "Expanda writing playground" to "Área de pruebas de escritura de Expanda"
)
